export const cuisines = [
    { display: 'African', value: 'african', imgUrl: '../assets/africa.jpg' },
    { display: 'Asian', value: 'asian',imgUrl: '../assets/africa.jpg' },
    { display: 'American', value: 'american',imgUrl: '../assets/africa.jpg' },
    { display: 'British', value: 'british',imgUrl: '../assets/africa.jpg' },
    { display: 'Cajun', value: 'cajun',imgUrl: '../assets/africa.jpg' },
    { display: 'Caribbean', value: 'caribbean',imgUrl: '../assets/africa.jpg' },
    { display: 'Chinese', value: 'chinese',imgUrl: '../assets/africa.jpg' },
    { display: 'Eastern European', value: 'eastern european',imgUrl: './assets/africa.jpg' },
    { display: 'European', value: 'european',imgUrl: '../assets/africa.jpg' },
    { display: 'French', value: 'french',imgUrl: '../assets/africa.jpg' },
    { display: 'German', value: 'german',imgUrl: '../assets/africa.jpg' },
    { display: 'Greek', value: 'greek',imgUrl: '../assets/africa.jpg' },
    { display: 'Indian', value: 'indian',imgUrl: '../assets/africa.jpg' },
    { display: 'Irish', value: 'irish',imgUrl: '../assets/africa.jpg' },
    { display: 'Italian', value: 'italian',imgUrl: '../assets/africa.jpg' },
    { display: 'Japanese', value: 'japanese',imgUrl: './assets/africa.jpg' },
    { display: 'Jewish', value: 'jewish',imgUrl: '../assets/africa.jpg' },
    { display: 'Korean', value: 'korean',imgUrl: '../assets/africa.jpg' },
    { display: 'Latin American', value: 'latin american',imgUrl: '../assets/africa.jpg' },
    { display: 'Mediterranean', value: 'mediterranean',imgUrl: '../assets/africa.jpg' },
    { display: 'Mexican', value: 'mexican',imgUrl: '../assets/africa.jpg' },
    { display: 'Middle Eastern', value: 'middle eastern',imgUrl: '../assets/africa.jpg' },
    { display: 'Nordic', value: 'nordic',imgUrl: '../assets/africa.jpg' },
    { display: 'Southern', value: 'southern',imgUrl: '../assets/africa.jpg' },
    { display: 'Spanish', value: 'spanish' ,imgUrl: '../assets/africa.jpg'},
    { display: 'Thai', value: 'thai',imgUrl: '../assets/africa.jpg' },
    { display: 'Vietnamese', value: 'vietnamese',imgUrl: '../assets/africa.jpg' },
  ];